excluded:
  - Pods
  - HostingApp/Strings.swift


disabled_rules:
  - todo

cyclomatic_complexity:
  ignores_case_statements: true

type_body_length:
  - 200 # warning
  - 360 # error

identifier_name:
  excluded:
    - i
    - j
    - id
    - x
    - y
    - db

line_length: 130
