excluded:
  - Pods
  - HostingApp/Strings.swift


disabled_rules:
  - todo

cyclomatic_complexity:
  ignores_case_statements: true

identifier_name:
  excluded:
    - i
    - id
    - x
    - y
    - db

line_length: 130
